### ISSUE TITLE
On Initial Pools for Deep Active Learning

### ISSUE THREAD

**Issue by kanzaali** [acl21/deep-active-learning-pytorch#1]
Hi, thank you so much for sharing your work. 
Can you please make a tutorial on how you made Figure 1 in On Initial Pools for Deep Active Learning. I am also interested to make such a graph for some active learning work.

**Comment by acl21** [comment]
Hi, 

I cannot make a tutorial explaining the code now but you can find the iPython notebook I used to generate the graphs [here](https://colab.research.google.com/drive/1kk7kEsiuctrwsNL4WciU1XVM_enJDbD3?usp=sharing). The code is straightforward and you should be able to understand it easily. 

Also, should you have any more questions about our initial pools paper, please raise an issue on this repo - https://github.com/acl21/init-pools-dal. Good luck!
