### ISSUE TITLE
How to run this project, no main.py 

### ISSUE THREAD

**Issue by kanzaali** [acl21/deep-active-learning-pytorch#2]
Kindly, guide us how to run this project and required args.parser

**Comment by acl21** [comment]
Please see this [Getting Started](https://github.com/acl21/deep-active-learning-pytorch/blob/main/docs/GETTING_STARTED.md) page for details on running this project.

**Comment by kanzaali** [comment]
Thank you so much, for ImageNet Tiny, where shall I give the path of the root folder? 
I am trying the following input 

CUDA_VISIBLE_DEVICES=0 python train_al.py --cfg=../configs/tinyimagenet/al/RESNET18.yaml --al=dbal --exp-name=vaal

Which is giving following error 

or x in os.scandir(self.root):
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/dataset/directory/'

**Comment by acl21** [comment]
You'd have to download the TinyImageNet dataset externally since torchvision doesn't download it for us. You can find the dataset [here](http://cs231n.stanford.edu/tiny-imagenet-200.zip).
